//
//  CompaniesData.swift
//  iTech Fair 2015
//
//  Created by Samer Salib on 2/15/15.
//  Copyright (c) 2015 Samer Salib. All rights reserved.
//

import Foundation



var companiesInfo:  [Company] = [
    Company(cmpName: "SE", cmpNumber: "34", cmpLocation: "Smyrna", cmpDetail: "It's for EE", cmpMajors: "EE", cmpDesiredDegreees: "BS", cmpWorkType: "Full-Time, Co-op", cmpWebsite:"" ),
    Company(cmpName: "Samson", cmpNumber: "67", cmpLocation: "Study Rooms", cmpDetail: "I love google, and swift.", cmpMajors: "CSC, CE",cmpDesiredDegreees: "Masters" , cmpWorkType: "Full-Time", cmpWebsite: "www.google.com") ,
    Company(cmpName: "Apple", cmpNumber: "94", cmpLocation: "Cali", cmpDetail: "The greatest", cmpMajors: "CSC, ECE", cmpDesiredDegreees: "PHD" , cmpWorkType: "Full-Time, Co-op, Internship", cmpWebsite: "www.Apple.com"),
    Company(cmpName: "ADTRAN", cmpNumber: "37", cmpLocation: "MPR", cmpDetail: "We are a leading global provider of networking and communications equipment. Our products enable voice, data, video and Internet communications across a variety of network infrastructures. Our solutions are currently in use by service providers, private enterprises, government organizations and millions of individual users worldwide.", cmpMajors: "CSC, Comp. Eng., EE", cmpDesiredDegreees: "BS", cmpWorkType: "Co-op, Full-Time", cmpWebsite: "http://www.adtran.com"),
    Company(cmpName: "Asurion", cmpNumber: "80", cmpLocation: "MPL", cmpDetail: "For the past 20 years, Asurion has helped people across the globe balance the interdependency between life and technology. Today, as the industry-defining leader of technology solutions, we ensure 280 million consumers' devices and appliances stay online and on the job in this fast-moving, tech-driven world.", cmpMajors: "Comp. Eng., CSC, ET, Finance, Mktg.", cmpDesiredDegreees: "BS", cmpWorkType: "Full-Time, Internship", cmpWebsite: "https://www.asurion.com"),
    Company(cmpName: "Bridgestone Americas – Warren Plant", cmpNumber: "38", cmpLocation: "MPR", cmpDetail: "The Bridgestone family of companies, which include Bridgestone Americas, is a world leader in tire and related technologies. The collective entities utilize the tri-polar research and development centers in Tokyo, Akron and Rome to produce advanced tire technologies for products that meet consumers’ needs. This continuing investment in research and development has resulted in new products incorporating the latest technology, like winter tire, better fuel economy and Run-Flat technology, for better, safer products.", cmpMajors: "CSC, EE, ME", cmpDesiredDegreees: "BS", cmpWorkType: "Full-Time, Co-op", cmpWebsite: "http://www.bridgestone-firestone.com"),
    Company(cmpName: "Dynetics, Inc.", cmpNumber: "116", cmpLocation: "TPR", cmpDetail: "Dynetics has delivered high-quality, high-value engineering, scientific, and information technology (IT) solutions to customers within the U.S. government and a range of other market segments since 1974. Dynetics delivers the \"Power of Solutions,\" providing complete lifecycle analysis, engineering, and hardware, to support customer missions. Our customers look to us for powerful solutions to their technical challenges in intelligence, missiles, aviation, cyber, and space.", cmpMajors: "Comp. Eng., CSC, EE", cmpDesiredDegreees: "BS, Masters", cmpWorkType: "Full-Time, Internship", cmpWebsite: "http://www.dynetics.com"),
    Company(cmpName: "EFC Systems, Inc.", cmpNumber: "56", cmpLocation: "MPR", cmpDetail: "EFC Systems delivers innovative software solutions throughout the entire Agribusiness supply chain. Our passionate team members employ modern technologies and anticipate industry trends to provide our client partners the tools and insight they need to manage their business.", cmpMajors: "Acct., Ag., Agribusiness Mgmt., Bus., Comp. Eng., CSC", cmpDesiredDegreees: "BS, Masters, MBA", cmpWorkType: "Full-Time, Internship", cmpWebsite: "http://www.efcsystems.com"),
    Company(cmpName: "Fast Enterprises, LLC", cmpNumber: "15", cmpLocation: "MPR", cmpDetail: "FAST started in 1997 with a vision to introduce packaged software to the integrated tax processing market. FAST is committed to being a premier provider of software and consulting services to government agencies.", cmpMajors: "CSC, Comp. Eng., Math", cmpDesiredDegreees: "BS", cmpWorkType: "Full-Time, Internship", cmpWebsite: "http://fastenterprises.com"),
    Company(cmpName: "Franklin American Mortgage Company", cmpNumber: "109", cmpLocation: "TPR", cmpDetail: "Founded in 1994, Franklin American Mortgage Company (FAMC), a privately-held mortgage banking firm located in Franklin, Tennessee, is a full-service professional mortgage banker licensed to provide residential mortgages across the nation. FAMC, which offers a host of diverse, flexible mortgage packages for customers with a variety of backgrounds and needs, is committed to helping families and individuals achieve the dream of home ownership through its three divisions: retail, wholesale and correspondent.", cmpMajors: "CSC", cmpDesiredDegreees: "BS, Masters", cmpWorkType: "Full-Time", cmpWebsite: "https://www.franklinamerican.com"),
    Company(cmpName: "Intergraph Corporation", cmpNumber: "", cmpLocation: "", cmpDetail: "The company’s software and solutions improve the lives of millions of people through better facilities, safer communities and more reliable operations. Intergraph Process, Power & Marine (PP&M) is the world’s leading provider of enterprise engineering software enabling smarter design and operation of plants, ships and offshore facilities. Intergraph Security, Government & Infrastructure (SG&I) is the leader in smart solutions for emergency response, utilities, transportation and other global challenges.", cmpMajors: "CSC", cmpDesiredDegreees: "BS", cmpWorkType: "Full-Time", cmpWebsite: "http://www.intergraph.com"),
    Company(cmpName: "IOMAXIS", cmpNumber: "87", cmpLocation: "MPL", cmpDetail: "Our efforts are focused on supporting the needs of our diverse Customer base quickly, regardless of where in the world our assistance is needed. From providing critical systems engineering to performing logistic support to difficult locations, IOMAXIS is committed to our Customers and to improving their organizational missions.", cmpMajors: "Comp. Eng., CSC, ET", cmpDesiredDegreees: "BS, Masters", cmpWorkType: "Full-Time, Co-op, Internship", cmpWebsite: "http://www.iomaxis.com"),
    Company(cmpName: "Jackson National Life Insurance Company", cmpNumber: "32", cmpLocation: "MPR", cmpDetail: "Implementing a customized retirement plan requires a company that recognizes the nuances. It requires a company that can make the complex understandable. The people at Jackson National Life Insurance Company® (\"Jackson®\") revel in this — from tax rates and withdrawal rates, to accumulation rates and mortality risks", cmpMajors: "Comp. Eng., CSC", cmpDesiredDegreees: "BS, Masters, MBA", cmpWorkType: "Full-Time, Internship", cmpWebsite: "https://www.jackson.com"),
        Company(cmpName: "Jewelry Television", cmpNumber: "121", cmpLocation: "1FL", cmpDetail: "Welcome to www.JTV.com, Jewelry Television®'s online shopping destination! Since 1993 our mission at Jewelry Television® has been to open the world of fine jewelry and gemstones to everyone. As the largest retailer of loose gemstones and one of the top 4 electronic jewelry retailers in the United States, we are confident we have the fine jewelry and gemstones you’re searching for!", cmpMajors: "Comp. Eng., CSC, ET, Math", cmpDesiredDegreees: "BS, Masters, PhD", cmpWorkType: "Full-Time, Co-op, Internship", cmpWebsite: "http://www.jtv.com"),
        Company(cmpName: "Manitowoc Walk-Ins", cmpNumber: "48", cmpLocation: "MPR", cmpDetail: "From modest beginnings in 1902 as a small shipbuilding and ship-repair company in Manitowoc, Wisconsin, through two world wars building ships and submarines for the U.S. Navy, to today – a global leader in cranes and foodservice equipment – The Manitowoc Company is here to stay. The vision of Manitowoc’s founding fathers, coupled with its core values of Integrity, Commitment to Stakeholders, and Passion for Excellence, have made Manitowoc a strong, respected organization throughout the world.", cmpMajors: "Bio-Mol. Eng., Chem. Eng., Civil Eng., Comp. Eng., CSC, EE, ET, ME", cmpDesiredDegreees: "BS", cmpWorkType: "Co-op, Internship", cmpWebsite: "http://www.manitowoc.com/EN/Pages/default.aspx"),
        Company(cmpName: "Medhost", cmpNumber: "18", cmpLocation: "MPR", cmpDetail: "For many reasons, the U.S. healthcare system is changing, and the changes are having a profound impact on the nation’s healthcare providers. MEDHOST, working with and gaining insight from its Customers, invests in software development that both reflects current requirements and anticipates needs often times in advance of marketplace demand.", cmpMajors: "Comp. Eng., CSC, EE", cmpDesiredDegreees: "BS", cmpWorkType: "Full-Time", cmpWebsite: "http://www.medhost.com" ),
        Company(cmpName: "Premier System Integrators", cmpNumber: "59", cmpLocation: "MPR", cmpDetail: "Founded in 1991 to provide turnkey system integration services for manufacturing facilities in the southeast, PREMIER System Integrators, Inc. has grown to be a multifaceted organization providing a wide range of services to manufacturers across the U.S. From its headquarters in Smyrna, TN, about 20 miles southeast of Nashville, PREMIER offers panel fabrication, consulting, outsourcing, recruiting, and other services in addition to its core business of industrial controls and factory information systems integration.", cmpMajors: "Comp. Eng., CSC, EE", cmpDesiredDegreees: "BS, Masters", cmpWorkType: "Full-Time, Co-op", cmpWebsite: "http://www.premier-system.com"),
        Company(cmpName: "Stanley, Black, & Decker, Inc.", cmpNumber: "70", cmpLocation: "MPR", cmpDetail: "The Stanley Fulfillment System (SFS) is our way of business. It's more than manufacturing or operational efficiency. It's a mindset, innovating how all work gets done and how we deliver value to the customer. An integral part of the culture, SFS encompasses and continually improves all of our business processes. It synchronizes the front end of the business with an ever-improving supply chain. It drives all practices toward best practices. It's how we generate capital from acquired assets to fuel further diversification and expansion.", cmpMajors: "Bus., EE, ET, Chem. Eng., Civil Eng., Comp. Eng., CSC, Math, ME", cmpDesiredDegreees: "BS, Masters, MBA", cmpWorkType: "Full-Time, Co-op, Internship", cmpWebsite: "http://www.stanleyblackanddecker.com"),
        Company(cmpName: "AMRDEC", cmpNumber: "117", cmpLocation: "1FL", cmpDetail: "The U. S. Army Aviation and Missile Research Development and Engineering Center (AMRDEC), a subordinate organization to the Research, Development and Engineering Command (RDECOM), is the Army’s focal point for providing research, development, and engineering technology and services for aviation and missile platforms across the lifecycle. AMRDEC has a long history of providing unparalleled service to its aviation and missile customers, while always striving to provide the greatest service to its ultimate customer, the warfighter, by providing technology and weapon system solutions to ensure his/her victory on the battlefield.", cmpMajors: "Comp. Eng., CSC, EE, ET, ME", cmpDesiredDegreees: "BS", cmpWorkType: "Full-Time", cmpWebsite: "http://www.amrdec.army.mil/amrdec/Directorates/SSDD.aspx"),
            Company(cmpName: "TAP Publishing Company", cmpNumber: "10", cmpLocation: "MPR", cmpDetail: "The same spirit of invention that pushed us into business inspires us today as we look to constantly improve our publications. In 1998, we added our first online-only service, weathertap.com, offering real-time weather on the internet. We will continue to look for ways to combine advancing technology and new markets with our tradition of superior products and services.", cmpMajors: "CSC", cmpDesiredDegreees: "BS, Masters", cmpWorkType: "Co-op, Full-Time, Internship", cmpWebsite: "http://www.tappublishing.com"),
            Company(cmpName: "Trane/Ingersoll Rand", cmpNumber: "30", cmpLocation: "MPR", cmpDetail: "At Trane, we're all about air – cool air, warm air, clean air. As a world leader in air conditioning systems, services and solutions, we control the comfort of the air for people in homes and many of the world’s largest and most famous commercial, industrial and institutional buildings. And we're applying Trane's expertise in environmental technology and energy conservation to make a difference in energy efficiency around the globe.", cmpMajors: "Bio-Mol. Eng., Chem. Eng., Civil Eng., Comp. Eng., CSC, EE, ET, ME", cmpDesiredDegreees: "BS", cmpWorkType: "Full-Time, Internship", cmpWebsite: "http://www.trane.com"),
            Company(cmpName: "Unum", cmpNumber: "33", cmpLocation: "MPR", cmpDetail: "We offer a full array of benefits solutions – including education, enrollment services and valuable claim support – to meet the needs of both employers and their workers. And our award-winning absence management and vocational rehabilitation services help ease the disruption to both businesses and employers by enabling them to return to full capacity as soon as they are able.", cmpMajors: "Business, Comp. Eng., CSC", cmpDesiredDegreees: "BS", cmpWorkType: "Full-Time, Internship", cmpWebsite: "http://www.unum.com"),
            Company(cmpName: "Urban Science", cmpNumber: "53", cmpLocation: "MPR", cmpDetail: "Urban Science is a business-solutions company focused on supporting the needs of the sales and marketing function of the automotive industry. We leverage a scientific methodology to help our client partners sell more vehicles, improve profitability and increase customer loyalty. And we do that by helping solve their toughest challenges including planning an optimal dealership network, improving individual dealer performance, and efficiently converting sales leads into sales. In short, we guide business through science—and we’ve been doing this since 1977.", cmpMajors: "Business, Comp. Eng., CSC", cmpDesiredDegreees: "BS", cmpWorkType: "Full-Time", cmpWebsite: "http://www.urbanscience.com")
    ]


/*class RecruitersParser{
    var filepath: String = ""
    var companiesInfoText: String = ""
    
    func readFile(fileName: String, fileType: String) -> String{
        var fileRoot = NSBundle.mainBundle().pathForResource(fileName, ofType: fileType)
        var contents = String(contentsOfFile: fileRoot!, encoding: NSUTF8StringEncoding, error: nil)
        if let contentText = contents{
            return contentText
        }else {return "File not found!"}
    }*/
    

    /*func setUpPath(){
            //let path = NSBundle.mainBundle().pathForResource("recruiters", ofType: "txt")
        //filepath = "~/recruiters.txt".stringByExpandingTildeInPath
        filepath = "recruiters.txt"
            if let path = filepath as String?{
                println("The path: \(path)")
                var error: NSErrorPointer = nil
                companiesInfoText = String(contentsOfFile: path, encoding: NSUTF8StringEncoding, error: error)!
            }else{
            print("path Doesn't exist")
            }
    }

    func printOut(){
     println(companiesInfoText)
    }
    
    func readData(fileName: String)->String{
        return ""
    }
}*/